{
  pkgs,
  pkgsStable,
  pkgsLatest,
  pkgsDarwin,
  ...
}:
{
  environment.systemPackages = with pkgs; [
          kitty
          vim
          git
          vscode
          stow
          stackit-cli
          utm
          fzf
          zoxide
          direnv
          starship
          eza
          yazi
          kubectl 
          direnv
          terraform
          zellij
          neovim
          tmux
          nodejs
          bat
          spotify
          obsidian
          gnumake
          logseq
          sketchybar
          zsh-autosuggestions
          zsh-fast-syntax-highlighting
          neofetch
          cyberduck
          cowsay
          yubikey-manager
          cloudfoundry-cli
          docker
          colima
  ];

  fonts.packages = with pkgs; [
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-emoji
    nerd-fonts._0xproto
    nerd-fonts.agave
    font-awesome
  ];
}
