config-version = 2

start-at-login = true
persistent-workspaces = ["1", "2", "10"]

after-login-command = []
after-startup-command = [
    "layout --workspace 1 --root h_tiles",
    "layout --workspace 2 --root h_tiles",
    "layout --workspace 10 --root h_tiles",
    "workspace 2",
    "workspace 1",
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = "tiles"
default-root-container-orientation = "horizontal"
automatically-unhide-macos-hidden-apps = true
on-focused-monitor-changed = []

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

[workspace-to-monitor-force-assignment]
1 = "main"
2 = ["secondary", "main"]
10 = "main"

# Hammerspoon is the only workflow binding owner.
[mode.main.binding]
