-- Run from the repository root: lua tests/hyprland_test.lua
package.path = "home/.config/hypr/?.lua;tests/?.lua;" .. package.path
local support = require("hyprland_support")
local windows = require("lib.window_navigation")
local text_launcher = require("lib.text_launcher")
local process = require("lib.process")
local modifier = "SUPER + CTRL + ALT + "
local project_path = assert(os.getenv("HOME")) .. "/dotfiles"
local passed = 0

local function picker_index(session, label)
    local request = assert(session.picker_request())
    local rows = assert(io.open(request.path))
    local index = 0
    for row in rows:lines() do
        if row == label then rows:close(); return index end
        index = index + 1
    end
    rows:close()
    error("Missing picker row: " .. label)
end

local function test(name, callback)
    local session = support.session()
    local ok, error_message = xpcall(function() callback(session) end, debug.traceback)
    session.close()
    assert(ok, name .. ": " .. tostring(error_message))
    passed = passed + 1
end

test("app selection replaces only the focused slot with a parked MRU instance", function(session)
    local left = session.add("kitty", 1, 0)
    local right = session.add("obsidian", 1, 3)
    local code = session.add("code", 10, 1)
    session.focus(left)
    session.press(modifier .. "K")
    assert(session.focused == code and code.workspace.id == 1 and code.layout.is_master)
    assert(left.workspace.id == 10 and right.workspace.id == 1 and not right.layout.is_master)
end)

test("selecting a visible instance swaps both screens without changing their slots", function(session)
    session.monitors[2].enabled = true
    local left = session.add("kitty", 1, 0)
    local right = session.add("obsidian", 1, 4)
    local remote_left = session.add("google-chrome", 2, 3)
    local remote_right = session.add("code", 2, 1)
    session.focus(left)
    session.press(modifier .. "K")
    assert(session.focused == remote_right and remote_right.workspace.id == 1 and remote_right.layout.is_master)
    assert(left.workspace.id == 2 and not left.layout.is_master)
    assert(remote_left.workspace.id == 2 and remote_left.layout.is_master and right.workspace.id == 1)
end)

test("Shift app creates a second slot and retains the first slot focus", function(session)
    local current = session.add("kitty", 1, 0)
    local code = session.add("code", 10, 1)
    session.focus(current)
    session.press(modifier .. "SHIFT + K")
    assert(session.focused == current and current.workspace.id == 1 and current.layout.is_master)
    assert(code.workspace.id == 1 and not code.layout.is_master)
end)

test("Shift app replaces the nonfocused left slot without creating a third slot", function(session)
    local left = session.add("kitty", 1, 2)
    local right = session.add("obsidian", 1, 0)
    local code = session.add("code", 10, 1)
    session.focus(right)
    session.press(modifier .. "SHIFT + K")
    assert(session.focused == right and not right.layout.is_master)
    assert(code.workspace.id == 1 and code.layout.is_master and left.workspace.id == 10)
end)

test("Shift app cannot duplicate the sole instance and prefers another instance", function(session)
    local current = session.add("code", 1, 0)
    session.focus(current)
    session.press(modifier .. "SHIFT + K")
    assert(#session.commands == 0 and session.focused == current)
    local other = session.add("code", 10, 1)
    session.press(modifier .. "SHIFT + K")
    assert(session.focused == current and other.workspace.id == 1)
end)

test("M focuses the other slot and N swaps contents while retaining the focused side", function(session)
    local left = session.add("code", 1)
    local right = session.add("kitty", 1)
    session.focus(left)
    session.press(modifier .. "M")
    assert(session.focused == right)
    session.press(modifier .. "N")
    assert(session.focused == left and not left.layout.is_master and right.layout.is_master)
end)

test("H follows the other display's active workspace instead of workspace numbers", function(session)
    session.monitors[2].enabled = true
    session.space(7).monitor = session.monitors[2]
    session.monitors[2].active_workspace = session.space(7)
    local current = session.add("kitty", 1, 0)
    session.add("code", 2, 1)
    local recent = session.add("google-chrome", 7, 2)
    session.add("obsidian", 7, 3)
    session.focus(current)
    session.press(modifier .. "H")
    assert(session.focused == recent and session.current.id == 7)
    session.press(modifier .. "H")
    assert(session.focused == current and session.monitors[2].active_workspace.id == 7)
end)

test("H handles an empty other display and a single display; G has no binding", function(session)
    local current = session.add("kitty", 1)
    session.focus(current)
    session.press(modifier .. "H")
    assert(session.focused == current and not session.bindings[modifier .. "G"])
    session.monitors[2].enabled = true
    session.press(modifier .. "H")
    assert(session.current.id == 2 and session.focused == nil)
    session.press(modifier .. "H")
    assert(session.focused == current)
end)

test("slash explicitly reduces to one slot without refilling it", function(session)
    local left = session.add("kitty", 1, 1)
    local right = session.add("code", 1, 0)
    session.focus(right)
    session.press(modifier .. "slash")
    session.flush()
    assert(session.focused == right and right.layout.is_master and left.workspace.id == 10)
end)

test("Shift slash restores the second slot from Parking without changing focus or ratio", function(session)
    local left = session.add("kitty", 1, 0)
    local right = session.add("code", 1, 2)
    local older = session.add("obsidian", 10, 3)
    session.focus(left)
    session.press(modifier .. "period"); session.press("M")
    session.press(modifier .. "slash")
    assert(right.workspace.id == 10 and session.focused == left)
    session.press(modifier .. "SHIFT + slash")
    assert(right.workspace.id == 1 and not right.layout.is_master)
    assert(session.focused == left and left.layout.is_master)
    assert(session.space(1).ratio == 0.5 and older.workspace.id == 10)
end)

test("Shift slash remembers an empty second slot for the next normal window", function(session)
    local current = session.add("kitty", 1, 0)
    session.focus(current)
    session.press(modifier .. "SHIFT + slash")
    assert(session.focused == current)
    local browser = session.open_window("google-chrome", 1, 1)
    session.flush()
    assert(browser.workspace.id == 1 and not browser.layout.is_master)
    assert(current.workspace.id == 1 and current.layout.is_master)
end)

test("dot M toggles the ratio per display and preserves the remembered single-window ratio", function(session)
    session.monitors[2].enabled = true
    local current = session.add("kitty", 1, 0)
    local code = session.add("code", 10, 1)
    local remote = session.add("google-chrome", 2, 2)
    session.focus(current)
    session.press(modifier .. "period"); session.press("M")
    assert(session.space(1).ratio == 0.5 and session.submap == "reset")
    session.press(modifier .. "SHIFT + K")
    assert(code.workspace.id == 1 and session.space(1).ratio == 0.5)
    session.press(modifier .. "H")
    assert(session.focused == remote and session.space(2).ratio == 0.7)
    session.press(modifier .. "H")
    session.press(modifier .. "period"); session.press("M")
    assert(session.space(1).ratio == 0.7)
end)

test("closing the focused master refills its side from Parking MRU and preserves the peer", function(session)
    local left = session.add("code", 1, 0)
    local right = session.add("kitty", 1, 4)
    local recent = session.add("google-chrome", 10, 1)
    local older = session.add("obsidian", 10, 3)
    session.focus(left)
    session.press(modifier .. "W")
    session.flush()
    assert(session.focused == recent and recent.layout.is_master)
    assert(right.workspace.id == 1 and not right.layout.is_master and older.workspace.id == 10)
end)

test("refill does not undo a later focus change to the other display", function(session)
    session.monitors[2].enabled = true
    local left = session.add("code", 1, 0)
    local right = session.add("kitty", 1, 2)
    local parked = session.add("obsidian", 10, 1)
    local remote = session.add("google-chrome", 2, 3)
    session.focus(left)
    session.close_window(left)
    session.focus(remote)
    session.flush()
    assert(session.focused == remote and session.current.id == 2)
    assert(parked.workspace.id == 1 and parked.layout.is_master)
    assert(right.workspace.id == 1 and not right.layout.is_master)
end)

test("background close refills without taking focus or using other visible windows", function(session)
    session.monitors[2].enabled = true
    local left = session.add("code", 1, 4)
    local right = session.add("kitty", 1, 3)
    local remote = session.add("google-chrome", 2, 0)
    local parked = session.add("obsidian", 10, 5)
    session.focus(left); session.focus(remote)
    session.close_window(right)
    session.flush()
    assert(session.focused == remote and remote.workspace.id == 2)
    assert(parked.workspace.id == 1 and not parked.layout.is_master and left.layout.is_master)
end)

test("no replacement remembers the missing side until a new normal window opens", function(session)
    local left = session.add("code", 1, 0)
    local right = session.add("kitty", 1, 1)
    session.focus(left)
    session.close_window(left)
    session.flush()
    assert(session.focused == right and right.layout.is_master)
    local browser = session.open_window("google-chrome", 1, 0)
    session.flush()
    assert(browser.layout.is_master and not right.layout.is_master and right.workspace.id == 1)
end)

test("dialogs and project overlays are excluded from replacement history", function(session)
    local current = session.add("code", 1, 0)
    local dialog = session.add("dialog", 10, 1); dialog.floating = true
    local overlay = session.add("project-overlay-terminal-1234", 10, 2)
    local parked = session.add("kitty", 10, 3)
    session.focus(current)
    session.close_window(current)
    session.flush()
    assert(session.focused == parked and dialog.workspace.id == 10 and overlay.workspace.id == 10)
end)

test("closing the nonfocused slot preserves keyboard focus on the other side", function(session)
    local left = session.add("code", 1, 0)
    local right = session.add("kitty", 1, 2)
    local parked = session.add("obsidian", 10, 1)
    session.focus(left)
    session.close_window(right); session.flush()
    assert(session.focused == left and left.layout.is_master)
    assert(parked.workspace.id == 1 and not parked.layout.is_master)
end)

test("closing both slots in one event batch refills both without duplicating windows", function(session)
    local left = session.add("code", 1, 0)
    local right = session.add("kitty", 1, 1)
    local a = session.add("obsidian", 10, 2)
    local b = session.add("google-chrome", 10, 3)
    session.focus(left)
    session.close_window(left); session.close_window(right); session.flush()
    assert(a.workspace.id == 1 and b.workspace.id == 1)
    assert(a.layout.is_master and not b.layout.is_master)
end)

test("hidden workspace selection parks the displaced target instead of swapping into hidden work", function(session)
    local current = session.add("kitty", 1, 0)
    session.space(3).monitor = session.monitors[1]
    local code = session.add("code", 3, 1)
    session.focus(current); session.press(modifier .. "K")
    assert(code.workspace.id == 1 and current.workspace.id == 10 and session.focused == code)
end)

test("a slot focus change prevents a delayed application from replacing the old target", function(session)
    local left = session.add("kitty", 1, 0)
    local right = session.add("obsidian", 1, 1)
    session.focus(left); session.press(modifier .. "K")
    session.focus(right)
    local code = session.add("code", 1, 2)
    session.emit("window.open", code); session.flush()
    assert(code.workspace.id == 10 and session.focused == right)
    assert(left.workspace.id == 1)
end)

test("external floating dialogs and overlays do not replace the current slot", function(session)
    local current = session.add("code", 1, 0)
    session.focus(current)
    local dialog = session.add("dialog", 1); dialog.floating = true
    session.emit("window.open_early", dialog); session.emit("window.open", dialog)
    local overlay = session.add("project-overlay-terminal-1234", 1)
    session.emit("window.open_early", overlay); session.emit("window.open", overlay)
    session.flush()
    assert(current.workspace.id == 1 and session.focused == current)
end)

test("external new windows replace the focused slot rather than adding a third tile", function(session)
    local left = session.add("code", 1, 1)
    local right = session.add("kitty", 1, 0)
    session.focus(right)
    local browser = session.open_window("google-chrome", 1, 0)
    session.flush()
    assert(session.focused == browser and not browser.layout.is_master)
    assert(left.workspace.id == 1 and right.workspace.id == 10)
end)

test("reload restores a vacant left slot and the display ratio from session data", function(session)
    local left = session.add("code", 1, 0)
    local right = session.add("kitty", 1, 1)
    session.focus(left)
    local path = os.tmpname()
    session.cleanup_paths = { path }
    local options = { parking = "10", list = windows.list, move = windows.move, state_file = path }
    local controller = require("lib.slot_layout").new(options)
    controller.toggle_ratio()
    session.close_window(left); session.flush()
    session.emit("config.unload")
    local restored = require("lib.slot_layout").new(options)
    local replacement = session.add("obsidian", 10, 2)
    restored.refill()
    assert(replacement.workspace.id == 1 and replacement.layout.is_master)
    assert(right.workspace.id == 1 and not right.layout.is_master and session.space(1).ratio == 0.5)
end)

test("initial adoption retains the master and focused window from a three-tile layout", function(session)
    local master = session.add("code", 1, 2)
    local excess = session.add("kitty", 1, 1)
    local focused = session.add("google-chrome", 1, 0)
    session.focus(focused)
    require("lib.slot_layout").new({ parking = "10", list = windows.list, move = windows.move })
    session.flush()
    assert(master.workspace.id == 1 and focused.workspace.id == 1)
    assert(excess.workspace.id == 10 and session.focused == focused)
end)

test("new application replaces its requested slot only after it appears", function(session)
    local current = session.add("kitty", 1, 0)
    session.focus(current)
    session.press(modifier .. "K")
    assert(current.workspace.id == 1 and #session.commands == 1)
    local code = session.add("code", 1, 1)
    session.emit("window.open", code); session.flush()
    assert(session.focused == code and current.workspace.id == 10)
end)

test("repeated launch requests use the latest other-slot preference", function(session)
    local current = session.add("kitty", 1, 0)
    session.focus(current)
    session.press(modifier .. "K")
    session.press(modifier .. "SHIFT + K")
    assert(#session.commands == 1 and session.commands[1].rules.no_initial_focus)
    local code = session.add("code", 1, 1)
    session.emit("window.open", code); session.flush()
    assert(session.focused == current and current.workspace.id == 1 and code.workspace.id == 1)
end)

test("a delayed class cannot briefly replace the focused slot before Shift placement", function(session)
    local current = session.add("kitty", 1, 0)
    local peer = session.add("obsidian", 1, 2)
    session.focus(current)
    session.press(modifier .. "SHIFT + K")
    local code = session.add("", 1, 1)
    session.emit("window.open_early", code)
    session.emit("window.open", code)
    session.flush()
    assert(current.workspace.id == 1 and peer.workspace.id == 1)
    code.class = "code"
    session.emit("window.class", code)
    session.flush()
    assert(current.workspace.id == 1 and session.focused == current)
    assert(code.workspace.id == 1 and peer.workspace.id == 10)
end)

test("superseded launches are parked without replacing a newer selection", function(session)
    local current = session.add("kitty", 1, 0)
    local chrome = session.add("google-chrome", 10, 1)
    session.focus(current)
    session.press(modifier .. "K"); session.press(modifier .. "L")
    local code = session.add("code", 1)
    session.emit("window.open", code); session.flush()
    assert(code.workspace.id == 10 and session.focused == chrome)
end)

test("monitor focus change invalidates a pending launch even after returning", function(session)
    session.monitors[2].enabled = true
    local current = session.add("kitty", 1, 0)
    session.focus(current)
    session.press(modifier .. "K"); session.press(modifier .. "H"); session.press(modifier .. "H")
    local code = session.add("code", 1)
    session.emit("window.open", code); session.flush()
    assert(code.workspace.id == 10 and session.focused == current)
end)

test("launch timeout allows retry and reports failure", function(session)
    session.press(modifier .. "K")
    session.flush(15000)
    assert(#session.notices == 1)
    session.press(modifier .. "K")
    assert(#session.commands == 2)
end)

test("instance picker opens for a single instance and replaces the selected slot", function(session)
    local current = session.add("kitty", 1, 0)
    local code = session.add("code", 10, 1)
    session.focus(current)
    session.held.f = true; session.press(modifier .. "K")
    assert(session.picker_request())
    session.choose(0)
    assert(session.focused == code and current.workspace.id == 10)
end)

test("Shift F selects a different instance for the other slot and retains focus", function(session)
    local current = session.add("code", 1, 0)
    local other = session.add("code", 10, 1)
    session.focus(current)
    session.held.f = true; session.press(modifier .. "SHIFT + K")
    session.choose(0)
    assert(session.focused == current and other.workspace.id == 1)
end)

test("P selects by MRU and Shift P targets the other slot", function(session)
    local current = session.add("kitty", 1, 0)
    local other = session.add("code", 10, 1)
    session.focus(current)
    session.press(modifier .. "SHIFT + P"); session.choose(0)
    assert(session.focused == current and other.workspace.id == 1)
    session.press(modifier .. "P"); session.choose(1)
    assert(session.focused == other and other.layout.is_master and current.workspace.id == 1)
end)

test("closed and reclassified windows cannot be selected", function(session)
    local code = session.add("code", 10)
    session.held.f = true; session.press(modifier .. "K")
    code.class = "other"; session.choose(0)
    assert(session.focused == nil)
    session.press(modifier .. "P"); code.mapped = false; session.choose(0)
    assert(session.focused == nil)
end)

test("quick comma release replaces only the focused slot", function(session)
    local current = session.add("kitty", 1, 0)
    local previous = session.add("code", 10, 1)
    local peer = session.add("obsidian", 1, 2)
    session.focus(current)
    session.press(modifier .. "comma"); session.press("Alt_L")
    assert(session.focused == previous and current.workspace.id == 10 and peer.workspace.id == 1)
end)

test("Shift comma reverses selection rather than targeting the other slot", function(session)
    local current = session.add("kitty", 1, 0)
    session.add("code", 10, 1)
    local last = session.add("obsidian", 10, 2)
    session.focus(current)
    session.press(modifier .. "SHIFT + comma"); session.press("Alt_L")
    assert(session.focused == last and current.workspace.id == 10 and last.layout.is_master)
end)

test("mapped cycles defer replacement until the Rofi layer has closed", function(session)
    local current = session.add("kitty", 1, 0)
    local code = session.add("code", 10, 1)
    session.focus(current); session.press(modifier .. "comma")
    local request = session.map_picker()
    rofi_picker_selected(request.token, 1)
    assert(session.focused == current and current.workspace.id == 1)
    session.emit("layer.closed", { pid = 5000 }); session.flush()
    assert(session.focused == code and current.workspace.id == 10)
end)

test("F comma filters instances of the current application", function(session)
    local current = session.add("unconfigured-app", 1, 0)
    local previous = session.add("Unconfigured-App", 10, 1)
    session.add("kitty", 10, 2)
    session.focus(current); session.held.f = true
    session.press(modifier .. "comma"); session.press("Alt_L")
    assert(session.focused == previous and current.workspace.id == 10)
end)

test("Escape cancels and stale callbacks cannot select a later picker", function(session)
    session.add("kitty", 1)
    session.press(modifier .. "comma")
    local stale = session.map_picker()
    session.press(modifier .. "Escape")
    session.press(modifier .. "P")
    rofi_picker_selected(stale.token, 0)
    session.emit("layer.closed", { pid = 5000 })
    session.flush()
    assert(session.focused == nil)
    assert(not io.open(stale.path))
end)

test("malformed and out-of-range selections do nothing", function(session)
    session.add("kitty", 1)
    for _, index in ipairs({ -1, 0.5, "0", 10 }) do
        session.press(modifier .. "P")
        session.choose(index)
        assert(session.focused == nil)
    end
end)

test("launcher startup failure cleans up and restores keybindings", function(session)
    session.add("kitty", 1)
    session.press(modifier .. "comma")
    local request = session.picker_request()
    session.flush(3000)
    assert(not io.open(request.path) and #session.notices == 1)
    assert(session.bindings[modifier .. "comma"].enabled)
end)

test("a new picker invalidates a result waiting for keyboard focus restoration", function(session)
    session.press(modifier .. "Y")
    local request = session.map_picker()
    rofi_picker_selected(request.token, 0)
    session.emit("layer.closed", { pid = 5000 })
    session.focus(session.add("code", 1))
    session.press(modifier .. "period")
    session.press("E")
    session.flush()
    for _, command in ipairs(session.commands) do assert(command.arguments[1] ~= "playerctl") end
end)

test("a reload discards a result waiting for keyboard focus restoration", function(session)
    session.press(modifier .. "Y")
    local request = session.map_picker()
    rofi_picker_selected(request.token, 0)
    session.emit("layer.closed", { pid = 5000 })
    session.emit("config.unload")
    session.flush()
    for _, command in ipairs(session.commands) do assert(command.arguments[1] ~= "playerctl") end
end)

test("B cycles regular workspaces by last focus", function(session)
    session.monitors[2].enabled = true
    session.space("special:test")
    session.press(modifier .. "H")
    session.press(modifier .. "H")
    session.press(modifier .. "B")
    session.press("Control_R")
    assert(session.current.id == 2)
end)

test("Shift B starts at the opposite end of the MRU list", function(session)
    session.press(modifier .. "SHIFT + B")
    session.press("Super_L")
    assert(session.current.id == 10)
end)

test("removed workspaces are not recreated by stale selection", function(session)
    session.press(modifier .. "B")
    session.spaces["2"] = nil
    session.choose(1)
    assert(session.current.id == 1 and not session.spaces["2"])
end)

test("Y starts with Play/Pause and is confirmed by a quick release", function(session)
    session.press(modifier .. "Y")
    session.press("Alt_R")
    local command = session.commands[#session.commands].arguments
    assert(command[1] == "playerctl" and command[3] == "spotify" and command[4] == "play-pause")
end)

test("Y has a fixed Next and Previous order after Play/Pause", function(session)
    for index, command in ipairs({ "next", "previous" }) do
        session.press(modifier .. "Y")
        session.choose(index)
        local arguments = session.commands[#session.commands].arguments
        assert(arguments[1] == "playerctl" and arguments[4] == command)
    end
end)

test("reverse Y starts at Previous", function(session)
    session.press(modifier .. "SHIFT + Y")
    session.press("Control_L")
    local arguments = session.commands[#session.commands].arguments
    assert(arguments[1] == "playerctl" and arguments[4] == "previous")
end)

test("text launchers preserve Unicode and snippet escapes", function()
    assert(text_launcher.emoji("👩🏽‍💻 woman technologist").text == "👩🏽‍💻")
    assert(text_launcher.snippet([[Hello\n\nHenrik|greeting]]).text == "Hello\n\nHenrik")
    assert(text_launcher.snippet([[literal \\n and \t|escape]]).text == "literal \\n and \t")
    assert(not text_launcher.snippet("invalid"))
end)

test("period E opens the emoji dataset and returns the selected emoji", function(session)
    session.focus(session.add("code", 1))
    session.press(modifier .. "period")
    session.press("E")
    session.choose(0)
    local arguments = session.commands[#session.commands].arguments
    assert(arguments[1] == "wtype" and arguments[2] == "--" and arguments[3] == "😀")
end)

test("text insertion is cancelled when the original window loses focus", function(session)
    session.focus(session.add("code", 1))
    session.press(modifier .. "period")
    session.press("T")
    session.focus(session.add("kitty", 1))
    session.choose(0)
    for _, command in ipairs(session.commands) do assert(command.arguments[1] ~= "wtype") end
end)

test("literal text remains one safely quoted command argument", function()
    local command = process.command({ "wtype", "--", "a'b $(touch /tmp/never) `false`\n-next" })
    assert(command == "'wtype' '--' 'a'\\''b $(touch /tmp/never) `false`\n-next'")
    assert(not pcall(process.command, { "wtype", "a\0b" }))
end)

test("dot mode stays visible until Q captures a region", function(session)
    assert(session.bindings[modifier .. "period"].options.dont_inhibit)
    assert(session.bindings["dot:Q"].options.dont_inhibit)
    session.press(modifier .. "period")
    assert(session.submap == "dot" and #session.commands == 0)
    local notice = session.notices[#session.notices]
    assert(notice.options.text == "dot mode" and notice.paused and notice.alive)
    session.press("Q")
    assert(session.submap == "reset" and not notice.alive)
    assert(table.concat(session.commands[1].arguments, " ") == "hyprshot --mode region")
end)

test("dot mode captures the active window with A and active output with Z", function(session)
    session.focus(session.add("code", 1))
    session.press(modifier .. "period")
    session.press("A")
    assert(session.submap == "reset")
    assert(table.concat(session.commands[1].arguments, " ") == "hyprshot --mode window --mode active")
    session.press(modifier .. "period")
    session.press("Z")
    assert(table.concat(session.commands[2].arguments, " ") == "hyprshot --mode output --mode active")
end)

test("Escape and unknown keys leave dot mode without capturing", function(session)
    for _, key in ipairs({ "Escape", "X" }) do
        session.press(modifier .. "period")
        session.press(key)
        assert(session.submap == "reset" and #session.commands == 0)
    end
end)

test("entering dot mode cancels pending Rofi selections", function(session)
    session.press(modifier .. "Y")
    local request = session.map_picker()
    session.press(modifier .. "period")
    rofi_picker_selected(request.token, 0)
    session.emit("layer.closed", { pid = 5000 })
    session.flush()
    for _, command in ipairs(session.commands) do assert(command.arguments[1] ~= "playerctl") end
    assert(session.submap == "dot")
end)

test("dispatch failures stop navigation before focus changes", function(session)
    local code = session.add("code", 2)
    code.fail_move = true
    assert(not pcall(session.press, modifier .. "SHIFT + K"))
    assert(session.focused == nil and code.workspace.id == 2)
end)

test("Ctrl shortcuts map browser actions to the focused Chrome window", function(session)
    local chrome = session.add("google-chrome", 1)
    session.focus(chrome)
    local expected = { p = { "CTRL SHIFT", "a" }, h = { "ALT", "Left" },
        j = { "CTRL SHIFT", "Tab" }, k = { "CTRL", "Tab" }, l = { "ALT", "Right" } }
    for key, shortcut in pairs(expected) do
        session.press("CTRL + " .. key)
        local actual = session.shortcuts[#session.shortcuts]
        assert(actual.mods == shortcut[1] and actual.key == shortcut[2] and actual.window == chrome)
    end
    assert(#session.commands == 0)
end)

test("Ctrl shortcuts follow focus and pass unchanged to other applications", function(session)
    session.focus(session.add("google-chrome", 1))
    session.press("CTRL + p")
    local editor = session.add("code", 1)
    session.focus(editor)
    for _, key in ipairs({ "p", "h", "j", "k", "l" }) do
        session.press("CTRL + " .. key)
        local actual = session.shortcuts[#session.shortcuts]
        assert(actual.mods == "CTRL" and actual.key == key and actual.window == editor)
    end
    editor.mapped = false
    session.press("CTRL + p")
    session.focus(nil)
    session.press("CTRL + p")
    assert(#session.shortcuts == 6)
end)

test("period R opens configured commands without a focused window and waits for selection", function(session)
    session.press(modifier .. "period")
    session.press("R")
    assert(session.submap == "reset" and #session.commands == 1)
    local request = session.map_picker()
    rofi_picker_selected(request.token, picker_index(session, "notify hallo"))
    assert(#session.commands == 1)
    session.emit("layer.closed", { namespace = "rofi", pid = 5000 })
    session.flush()
    local arguments = session.commands[#session.commands].arguments
    assert(arguments[1] == "bash" and arguments[2] == "-c" and arguments[3] == 'notify-send "Hallo"')
end)

test("workspace reset restores displays and focuses the terminal workspace", function(session)
    require("lib.monitor_configuration").set_workspace_roles({
        primary = "HDMI-A-1", secondary = "HDMI-A-2",
    })
    session.monitors[2].enabled = true
    local code = session.add("code", 1, 0)
    local terminal = session.add("kitty", 10, 1)
    session.focus(code)
    session.press(modifier .. "period")
    session.press("R")
    session.choose(picker_index(session, "reset workspaces"))

    assert(session.spaces["1"].monitor.name == "HDMI-A-1")
    assert(session.spaces["2"].monitor.name == "HDMI-A-2")
    assert(session.spaces["10"].monitor.name == "HDMI-A-1")
    assert(session.current == session.spaces["1"] and session.focused == terminal)
    assert(terminal.workspace == session.spaces["1"] and code.workspace == session.spaces["10"])
end)

test("command cancellation never starts a configured command", function(session)
    session.press(modifier .. "period")
    session.press("R")
    session.map_picker()
    session.emit("layer.closed", { namespace = "rofi", pid = 5000 })
    session.flush()
    assert(#session.commands == 1)
end)

test("command data preserves shell syntax and duplicate labels retain row identity", function(session)
    local commands = require("lib.command_launcher")
    local picker = require("lib.rofi_picker").new({ modifier = "SHIFT", rows = 5, provider = "provider.lua" })
    local path = os.tmpname()
    local file = assert(io.open(path, "w"))
    file:write("\r\ninvalid\n |empty command\ntrue|   \n",
        "printf '%s' 'first'|duplicate\r\n",
        "printf '%s' '$HOME' | cat|duplicate\r\n")
    file:close()
    commands.open(picker, path)
    os.remove(path)
    local rows = assert(io.open(session.picker_request().path))
    assert(rows:read("*a") == "duplicate\nduplicate\n")
    rows:close()
    session.choose(1)
    assert(session.commands[#session.commands].arguments[3] == "printf '%s' '$HOME' | cat")
end)

test("period T inserts snippets and direct R remains the application launcher", function(session)
    session.focus(session.add("code", 1))
    session.press(modifier .. "period")
    session.press("T")
    assert(session.submap == "reset")
    session.choose(0)
    assert(session.commands[#session.commands].arguments[1] == "wtype")
    session.press(modifier .. "R")
    assert(table.concat(session.commands[#session.commands].arguments, " ") == "rofi -show drun")
    assert(not session.bindings[modifier .. "E"] and not session.bindings[modifier .. "Q"])
end)

test("Shift R opens a read-only catalog with global, dot mode and hardware shortcuts", function(session)
    session.press(modifier .. "SHIFT + R")
    local request = assert(session.picker_request())
    local rows = assert(io.open(request.path))
    local labels = rows:read("*a")
    rows:close()

    assert(labels:find("MainMod + J — Fill focused slot with Kitty / Zellij", 1, true))
    assert(labels:find("MainMod + Shift + R — Show shortcut catalog", 1, true))
    assert(labels:find("MainMod + B — Cycle workspaces by last focus", 1, true))
    assert(not labels:find("MainMod + G +", 1, true))
    assert(labels:find("MainMod + . → M — Toggle display split between 70:30 and 50:50", 1, true))
    assert(labels:find("MainMod + . → Q — Capture region", 1, true))
    assert(labels:find("XF86AudioRaiseVolume — Raise volume", 1, true))
    assert(not labels:find("catchall", 1, true))

    session.choose(0)
    assert(#session.shortcuts == 0)
end)

test("dot B shows display status and enables the selected output", function(session)
    session.press(modifier .. "period")
    session.press("B")
    local request = assert(session.picker_request())
    local rows = assert(io.open(request.path))
    local labels = rows:read("*a")
    rows:close()
    assert(labels:find("🟢 HDMI%-A%-1 · enabled") and labels:find("⚫ HDMI%-A%-2 · disabled"))
    session.choose(1)
    assert(session.monitors[2].enabled)
    assert(session.monitor_rules[#session.monitor_rules].output == "HDMI-A-2")
end)

test("dot B refuses to disable the last active display", function(session)
    session.press(modifier .. "period")
    session.press("B")
    session.choose(0)
    assert(session.monitors[1].enabled and #session.monitor_rules == 0)
    assert(session.notices[#session.notices].options.text == "The last enabled display must remain on.")
end)

test("project overlays reuse one floating Kitty window per project and tool", function(session)
    local code = session.add("code", 1)
    code.title = project_path .. " | Code"
    session.focus(code)
    session.press(modifier .. "period")
    session.press("J")
    local launch = session.commands[#session.commands]
    local class
    for index, argument in ipairs(launch.arguments) do
        if argument == "--class" then class = launch.arguments[index + 1] end
    end
    assert(class and launch.arguments[#launch.arguments] == "zsh")
    assert(launch.rules.no_initial_focus)
    local terminal = session.add(class, 1)
    session.emit("window.open", terminal)
    session.flush(50)
    session.flush(30)
    session.flush(30)
    session.flush(30)
    assert(session.focused == terminal and terminal.floating)
    assert(terminal.centered and terminal.size[1] == 1824 and terminal.size[2] == 972 and session.group_denied)
    session.press(modifier .. "period")
    session.press("J")
    assert(terminal.workspace.addressable_name == "special:project-overlays")
    assert(#session.commands == 1)
end)

test("project overlays remain floating across repeated hide and restore cycles", function(session)
    local code = session.add("code", 1)
    code.title = project_path .. " | Code"
    session.focus(code)
    session.press(modifier .. "period")
    session.press("J")
    local launch = session.commands[#session.commands]
    local class
    for index, argument in ipairs(launch.arguments) do
        if argument == "--class" then class = launch.arguments[index + 1] end
    end
    local terminal = session.add(assert(class), 1)
    terminal.retile_on_move = true
    session.emit("window.open", terminal)
    session.flush(50)
    for _ = 1, 3 do session.flush(30) end

    for _ = 1, 3 do
        assert(terminal.workspace.addressable_name == "1" and terminal.floating and terminal.centered)
        session.press(modifier .. "period")
        session.press("J")
        assert(terminal.workspace.addressable_name == "special:project-overlays")
        terminal.centered = false
        session.focus(code)
        session.press(modifier .. "period")
        session.press("J")
        session.flush(30)
        session.flush(30)
        session.retile_on_next_center(terminal)
        session.flush(30)
        session.flush(30)
        session.flush(30)
        session.flush(30)
    end
    assert(terminal.workspace.addressable_name == "1" and terminal.floating and terminal.centered)
    assert(#session.commands == 1)
end)

test("dot G opens LazyVim and Shift G opens Lazygit for the active project", function(session)
    local code = session.add("code", 1)
    code.title = project_path .. " | Code"
    session.focus(code)
    for _, expected in ipairs({ { "G", "nvim" }, { "SHIFT + G", "lazygit" } }) do
        session.press(modifier .. "period")
        session.press(expected[1])
        assert(session.commands[#session.commands].arguments[#session.commands[#session.commands].arguments] == expected[2])
    end
end)

print(string.format("%d Hyprland scenarios passed", passed))
